import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  MatToolbarModule,
  MatButtonModule,
  MatIconModule,
  MatSidenavModule,
  MatListModule,
  MatExpansionModule,
  MatCardModule,
  MatProgressBarModule,
  MatPaginatorModule,
  MatDialogModule,
  MatProgressSpinnerModule,
  MatInputModule,
  MatCheckboxModule,
  MatMenuModule,
  MatTabsModule,
  MatSnackBarModule,
  MatStepperModule,
  MatFormFieldModule,
  MatAutocompleteModule,
  MatTableModule } from '@angular/material';

@NgModule({
  imports: [
    FormsModule,
    ReactiveFormsModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatExpansionModule,
    MatCardModule,
    MatProgressBarModule,
    MatPaginatorModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatInputModule,
    MatCheckboxModule,
    MatMenuModule,
    MatTabsModule,
    MatSnackBarModule,
    MatStepperModule,
    MatFormFieldModule,
    MatAutocompleteModule,
    MatTableModule
  ],
  exports: [
    FormsModule,
    ReactiveFormsModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatExpansionModule,
    MatCardModule,
    MatProgressBarModule,
    MatPaginatorModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatInputModule,
    MatCheckboxModule,
    MatMenuModule,
    MatTabsModule,
    MatSnackBarModule,
    MatStepperModule,
    MatFormFieldModule,
    MatAutocompleteModule,
    MatTableModule
  ]
})
export class SharedModule { }
